/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated.policies'
import { Route as AuthenticatedGraphV3RouteImport } from './routes/_authenticated.graph-v3'
import { Route as AuthenticatedConnectorsRouteImport } from './routes/_authenticated.connectors'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated.audit-log'
import { Route as AuthenticatedChangesIndexRouteImport } from './routes/_authenticated.changes.index'
import { Route as AuthenticatedChangesIdRouteImport } from './routes/_authenticated.changes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGraphV3Route = AuthenticatedGraphV3RouteImport.update({
  id: '/graph-v3',
  path: '/graph-v3',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectorsRoute = AuthenticatedConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangesIndexRoute =
  AuthenticatedChangesIndexRouteImport.update({
    id: '/changes/',
    path: '/changes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChangesIdRoute = AuthenticatedChangesIdRouteImport.update({
  id: '/changes/$id',
  path: '/changes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/graph-v3': typeof AuthenticatedGraphV3Route
  '/policies': typeof AuthenticatedPoliciesRoute
  '/changes/$id': typeof AuthenticatedChangesIdRoute
  '/changes/': typeof AuthenticatedChangesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/connectors': typeof AuthenticatedConnectorsRoute
  '/graph-v3': typeof AuthenticatedGraphV3Route
  '/policies': typeof AuthenticatedPoliciesRoute
  '/': typeof AuthenticatedIndexRoute
  '/changes/$id': typeof AuthenticatedChangesIdRoute
  '/changes': typeof AuthenticatedChangesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/connectors': typeof AuthenticatedConnectorsRoute
  '/_authenticated/graph-v3': typeof AuthenticatedGraphV3Route
  '/_authenticated/policies': typeof AuthenticatedPoliciesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/changes/$id': typeof AuthenticatedChangesIdRoute
  '/_authenticated/changes/': typeof AuthenticatedChangesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-log'
    | '/connectors'
    | '/graph-v3'
    | '/policies'
    | '/changes/$id'
    | '/changes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit-log'
    | '/connectors'
    | '/graph-v3'
    | '/policies'
    | '/'
    | '/changes/$id'
    | '/changes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/audit-log'
    | '/_authenticated/connectors'
    | '/_authenticated/graph-v3'
    | '/_authenticated/policies'
    | '/_authenticated/'
    | '/_authenticated/changes/$id'
    | '/_authenticated/changes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/graph-v3': {
      id: '/_authenticated/graph-v3'
      path: '/graph-v3'
      fullPath: '/graph-v3'
      preLoaderRoute: typeof AuthenticatedGraphV3RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connectors': {
      id: '/_authenticated/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AuthenticatedConnectorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changes/': {
      id: '/_authenticated/changes/'
      path: '/changes'
      fullPath: '/changes/'
      preLoaderRoute: typeof AuthenticatedChangesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changes/$id': {
      id: '/_authenticated/changes/$id'
      path: '/changes/$id'
      fullPath: '/changes/$id'
      preLoaderRoute: typeof AuthenticatedChangesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedConnectorsRoute: typeof AuthenticatedConnectorsRoute
  AuthenticatedGraphV3Route: typeof AuthenticatedGraphV3Route
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChangesIdRoute: typeof AuthenticatedChangesIdRoute
  AuthenticatedChangesIndexRoute: typeof AuthenticatedChangesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedConnectorsRoute: AuthenticatedConnectorsRoute,
  AuthenticatedGraphV3Route: AuthenticatedGraphV3Route,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChangesIdRoute: AuthenticatedChangesIdRoute,
  AuthenticatedChangesIndexRoute: AuthenticatedChangesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
